"""Dataset of Menu Items"""
mcdonalds_menu = {
    "McChicken",
    "Mac Chicken",
    "McCrispy",
    "Mac Crispy",
    "Big Mac",
    "Coke",
    "Sprite"
    "McToast",
    "Mac Toast",
    "BLT Quarter Pounder",
    "Bacon Habanero Ranch Quarter Pounder",
    "Bacon & Cheese Quarter Pounder",
    "Deluxe Quarter Pounder",
    "Double Quarter Pounder with Cheese",
    "Hamburger",
    "Cheeseburger",
    "Grilled Onion Cheddar Burger",
    "Double Cheeseburger",
    "McDouble",
    "Mac Double"
    "Daily Double",
    "McRib",
    "Premium McWrap Chicken & Bacon",
    "Premium McWrap Chicken & Ranch",
    "Premium McWrap Sweet Chili Chicken",
    "Chipotle BBQ Snack Wrap",
    "Honey Mustard Snack Wrap",
    "Ranch Snack Wrap",
    "Ranch Snack Wrap (Grilled)",
    "Mac Snack Wrap",
    "Chicken McNuggets",
    "Premium Crispy Chicken Classic Sandwich",
    "Premium Grilled Chicken Classic Sandwich",
    "Premium Crispy Chicken Club Sandwich",
    "Premium Grilled Chicken Club Sandwich",
    "Premium Crispy Chicken Ranch BLT Sandwich",
    "Premium Grilled Chicken Ranch BLT Sandwich",
    "Southern Style Crispy Chicken Sandwich",
    "Filet-O-Fish",
    "Premium Bacon Ranch Salad",
    "Premium Bacon Ranch Salad with Crispy Chicken",
    "Premium Bacon Ranch Salad with Grilled Chicken",
    "Premium Caesar Salad",
    "Premium Caesar Salad with Crispy Chicken",
    "Premium Caesar Salad with Grilled Chicken",
    "Premium Southwest Salad",
    "Premium Southwest Salad with Crispy Chicken",
    "Premium Southwest Salad with Grilled Chicken",
    "Side Salad",
    "Fruit & Maple Oatmeal",
    "Egg McMuffin",
    "Egg White Delight McMuffin",
    "Sausage McMuffin",
    "Sausage McMuffin with Egg",
    "Steak, Egg & Cheese McMuffin",
    "Bacon, Egg & Cheese Biscuit",
    "Sausage Biscuit",
    "Sausage Biscuit with Egg",
    "Sausage McGriddles",
    "Sausage, Egg & Cheese McGriddles",
    "Bacon, Egg & Cheese Bagel",
    "Steak, Egg & Cheese Bagel",
    "Big Breakfast",
    "Big Breakfast with Hotcakes",
    "Cinnamon Melts",
    "Hotcakes",
    "Hotcakes and Sausage",
    "Southern Style Chicken Biscuit",
    "Sausage Burrito",
    "Hash Browns",
    "French Fries",
    "Premium Roast Coffee",
    "McCafé Latte",
    "McCafé Mocha",
    "McCafé Caramel Mocha",
    "McCafé Hot Chocolate",
    "Premium Roast Iced Coffee",
    "McCafé Iced Mocha",
    "McCafé Iced Caramel Mocha",
    "McCafé Frappé Mocha",
    "McCafé Frappé Caramel",
    "McCafé Frappé Chocolate Chip",
    "McCafé Blueberry Pomegranate Smoothie",
    "McCafé Strawberry Banana Smoothie",
    "McCafé Mango Pineapple Smoothie",
    "McCafé Frozen Strawberry Lemonade",
    "McCafé Cherry Berry Chiller",
    "McCafé Vanilla Shake",
    "McCafé Chocolate Shake",
    "McCafé Strawberry Shake",
    "McCafé Dulce de Leche Shake",
    "Vanilla Cone",
    "Kiddie Cone",
    "Hot Fudge Sundae",
    "Hot Caramel Sundae",
    "Strawberry Sundae",
    "McFlurry with M&M's®",
    "McFlurry with OREO® Cookies",
    "Baked Apple Pie",
    "Soft Baked Chocolate Chip Cookie",
    "Soft Baked Oatmeal Raisin Cookie"
}
