# Generated by Django 5.0 on 2023-12-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aparro_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Record",),
    ]
